"source": [
        "# ----------------- Student Management System (Streamlit App) ----------------- #\n",
        "\n",
        "import streamlit as st\n",
        "import csv\n",
        "import os\n",
        "import pandas as pd\n",
        "\n",
        "# ----------------- CSV Setup ----------------- #\n",
        "FILENAME = \"students.csv\"\n",
        "\n",
        "if not os.path.exists(FILENAME):\n",
        "    with open(FILENAME, mode='w', newline='') as file:\n",
        "        writer = csv.writer(file)\n",
        "        writer.writerow([\"VID\", \"Name\", \"Citizen\", \"Course\", \"Status\"])\n",
        "\n",
        "# ----------------- Functions ----------------- #\n",
        "\n",
        "def add_student(vid, name, citizen, course, status):\n",
        "    with open(FILENAME, mode='a', newline='') as file:\n",
        "        writer = csv.writer(file)\n",
        "        writer.writerow([vid, name, citizen, course, status])\n",
        "\n",
        "def read_student(vid):\n",
        "    df = pd.read_csv(FILENAME)\n",
        "    return df[df[\"VID\"] == vid]\n",
        "\n",
        "def update_student(vid, name, citizen, course, status):\n",
        "    df = pd.read_csv(FILENAME)\n",
        "    if vid in df[\"VID\"].values:\n",
        "        df.loc[df[\"VID\"] == vid, [\"Name\",\"Citizen\",\"Course\",\"Status\"]] = [\n",
        "            name, citizen, course, status\n",
        "        ]\n",
        "        df.to_csv(FILENAME, index=False)\n",
        "        return True\n",
        "    return False\n",
        "\n",
        "def delete_student(vid):\n",
        "    df = pd.read_csv(FILENAME)\n",
        "    if vid in df[\"VID\"].values:\n",
        "        df = df[df[\"VID\"] != vid]\n",
        "        df.to_csv(FILENAME, index=False)\n",
        "        return True\n",
        "    return False\n",
        "\n",
        "def show_all_students():\n",
        "    return pd.read_csv(FILENAME)\n",
        "\n",
        "# ----------------- Streamlit UI ----------------- #\n",
        "\n",
        "st.title(\"🎓 Student Management System\")\n",
        "\n",
        "menu = st.sidebar.selectbox(\n",
        "    \"Select Operation\",\n",
        "    [\"Add Student\", \"View Student\", \"Update Student\", \"Delete Student\", \"Show All Students\"]\n",
        ")\n",
        "\n",
        "# -------- Add Student -------- #\n",
        "if menu == \"Add Student\":\n",
        "    st.subheader(\"➕ Add New Student\")\n",
        "    vid = st.number_input(\"VID\", min_value=1)\n",
        "    name = st.text_input(\"Name\")\n",
        "    citizen = st.text_input(\"Citizen\")\n",
        "    course = st.text_input(\"Course\")\n",
        "    status = st.text_input(\"Status\")\n",
        "\n",
        "    if st.button(\"Add Student\"):\n",
        "        add_student(vid, name, citizen, course, status)\n",
        "        st.success(\"Student added successfully!\")\n",
        "\n",
        "# -------- View Student -------- #\n",
        "elif menu == \"View Student\":\n",
        "    st.subheader(\"🔍 View Student Record\")\n",
        "    vid = st.number_input(\"Enter VID\", min_value=1)\n",
        "\n",
        "    if st.button(\"Search\"):\n",
        "        result = read_student(vid)\n",
        "        if not result.empty:\n",
        "            st.dataframe(result)\n",
        "        else:\n",
        "            st.warning(\"Student not found\")\n",
        "\n",
        "# -------- Update Student -------- #\n",
        "elif menu == \"Update Student\":\n",
        "    st.subheader(\"✏️ Update Student Record\")\n",
        "    vid = st.number_input(\"VID\", min_value=1)\n",
        "    name = st.text_input(\"New Name\")\n",
        "    citizen = st.text_input(\"New Citizen\")\n",
        "    course = st.text_input(\"New Course\")\n",
        "    status = st.text_input(\"New Status\")\n",
        "\n",
        "    if st.button(\"Update\"):\n",
        "        if update_student(vid, name, citizen, course, status):\n",
        "            st.success(\"Student updated successfully!\")\n",
        "        else:\n",
        "            st.error(\"Student not found\")\n",
        "\n",
        "# -------- Delete Student -------- #\n",
        "elif menu == \"Delete Student\":\n",
        "    st.subheader(\"🗑️ Delete Student\")\n",
        "    vid = st.number_input(\"VID to delete\", min_value=1)\n",
        "\n",
        "    if st.button(\"Delete\"):\n",
        "        if delete_student(vid):\n",
        "            st.success(\"Student deleted successfully!\")\n",
        "        else:\n",
        "            st.error(\"Student not found\")\n",
        "\n",
        "# -------- Show All Students -------- #\n",
        "elif menu == \"Show All Students\":\n",
        "    st.subheader(\"📋 All Student Records\")\n",
        "    df = show_all_students()\n",
        "    if df.empty:\n",
        "        st.warning(\"No records available\")\n",
        "    else:\n",
        "        st.dataframe(df)\n"
      ]
    },
    {
      "cell_type": "code",
      "source": [],
      "metadata": {
        "id": "Kzy3jg4GadCY"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}
